!ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 3
  - 3
  - 3
name: net.0.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: net.1.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 16
  - 3
  - 3
name: net.2.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: net.3.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: net.4.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 32
  - 3
  - 3
name: net.5.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 64
  - 3
  - 3
name: net.6.block.0
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 12
  - 64
name: net.9
qgranularityspec: PER-ARRAY
qhinitparam: MINMAX
