!ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 3
  - 3
  - 3
name: conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: layer1.0.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: layer1.0.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: layer1.1.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: layer1.1.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: layer1.2.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 16
  - 16
  - 3
  - 3
name: layer1.2.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 16
  - 3
  - 3
name: layer2.0.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: layer2.0.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 16
  - 1
  - 1
name: layer2.0.shortcut.0
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: layer2.1.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: layer2.1.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: layer2.2.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 32
  - 32
  - 3
  - 3
name: layer2.2.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 32
  - 3
  - 3
name: layer3.0.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 64
  - 3
  - 3
name: layer3.0.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 32
  - 1
  - 1
name: layer3.0.shortcut.0
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 64
  - 3
  - 3
name: layer3.1.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 64
  - 3
  - 3
name: layer3.1.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 64
  - 3
  - 3
name: layer3.2.conv1
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 64
  - 64
  - 3
  - 3
name: layer3.2.conv2
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
--- !ModuleDescriptor
core_choice: DIGITAL
kernel_size: !!python/object/apply:torch.Size
- !!python/tuple
  - 10
  - 64
name: linear
qgranularityspec: PER-ARRAY
qhinitparam: MEANSTD
